//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLANTA
    {
        public int idllanta { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> iddet { get; set; }
        public string codllanta { get; set; }
        public Nullable<int> idmarca { get; set; }
        public Nullable<int> idmodelo { get; set; }
        public Nullable<int> idmedida { get; set; }
        public Nullable<int> remanente { get; set; }
        public Nullable<int> posicion { get; set; }
        public Nullable<int> kminstalacion { get; set; }
        public Nullable<int> nroreencauche { get; set; }
        public Nullable<int> idalmacen { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> remanenteoriginal { get; set; }
        public Nullable<int> remanentereencauche { get; set; }
    }
}
