//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMANENTE
    {
        public int idremanente { get; set; }
        public string codllanta { get; set; }
        public string fechainspeccion { get; set; }
        public Nullable<int> kminspeccion { get; set; }
        public Nullable<int> remanenteactual { get; set; }
        public string estadooperacion { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
    }
}
